version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    allow:
      - dependency-type: "all"
    rebase-strategy: "auto"
    schedule:
      interval: "weekly"
      day: "sunday"
    versioning-strategy: "auto"
    
 - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # Ignore updates to packages that start with 'aws'
      # Wildcards match zero or more arbitrary characters
      - dependency-name: "aws*"
      # Ignore some updates to the 'express' package
      - dependency-name: "express"
        # Ignore only new versions for 4.x and 5.x
        versions: ["4.x", "5.x"]
      # For all packages, ignore all patch updates
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
